### PR TITLE
Display and edit jobs

### PR DESCRIPTION
**Pull request by kierancott**
### Changelog:

- Can now add a job to database using add a job form
- Can now add interviews and application notes to that job on the same page
- Can now modify job details from single job page
- Can now modify CV and cover letter from single job page
- Can now add, edit and delete application notes from single job page
- Can now add, edit and delete interviews from single job page
- Can now delete a job
- Can now update stage using stage tracker on main page

### CODE REVIEW

**Review by nosvalds — CHANGES_REQUESTED** [review]
## Issues found while testing
- Job ID doesn't seem to be added to URL for the PATCH request when editing a single job. Potentially because the job info is being stored in state as job.data.data.id not job.id?
 
image

image

- When I click the "Add note" button the POST request is triggered right away. I don't see a place where I can add in note information to be POST'd. Additionally the API Key is not included in the header so I get an unauthenticated response
image

image

- Same as the above issue but for "Add Interview"
image

- After going through the process of adding a new job in the Modal. I click outside the Modal window to go back to the /mainpage and my new job is not there. I have to refresh the page for the newly added job to show.

- When I am in the edit single job page, the header has disappeared so I can't navigate back to the /mainpage or check my account, etc.
image

**Comment by kierancott** [comment]
## Updated

**Issue:**
_"When I click the "Add Interview" button the POST request is triggered right away. I don't see a place where I can add in interview information to be POST'd. Additionally the API Key is not included in the header so I get an unauthenticated response"_

**Action:**
Created a form that dispatches a POST request to `api/users/id/jobs/id/interviews` with new interview data

Screenshot 2020-10-08 at 16 45 08

Screenshot 2020-10-08 at 16 44 58

Screenshot 2020-10-08 at 16 45 32

Screenshot 2020-10-08 at 16 45 45

Screenshot 2020-10-08 at 16 45 53

---

**Issue:**
"_When I am in the edit single job page, there isn't a clear way to navigate back to the /mainpage. Looks like you can got to Account > My Applications - happy to leave this for MVP, but could add a button somewhere_"

**Action:**
Added a button that directs back to the main page - will need to be styled with CSS so that it is not right next to the delete job button

Screenshot 2020-10-08 at 16 46 20

---
Screenshot 2020-10-08 at 16 51 01

**Issue:** 
_"Clicking to advance the green application stage indicators works visually, but I don't see any PATCH requests to the backend to change the stage value"_

**Action:**
Wrapped the status circle in a `<div>` that handles the colour change, the status circle itself sends a patch request. The `<div>` wrapper itself will need to be styled such that you cannot click the `<div>` without also clicking the status circle, which is currently not the case.

However, clicking the status circle itself now changes the colour, and sends a patch request for the correct `job_id`.

Screenshot 2020-10-08 at 16 50 46


Screenshot 2020-10-08 at 16 51 01

**Review by nosvalds — CHANGES_REQUESTED** [review]
Looking good!!
## Fixed
- Back button works well
- I'm able to add an interview 
- Status changing works and send post requests

## To do
- If I add an interview but don't change the "format" drop down the client doesn't include the format in the POST request and fails
image
image

- DELETE interview is failing as Unauthorized
image

**Review by nosvalds — CHANGES_REQUESTED** [review]
## Resolved
- Adding an interview without changing the format now works appropriately
- DELETE works for interviews now

## Issues Encountered
- I did a test of adding a new job to a newly registered user and received this error when going to the 2nd Form of the Modal. Looks like your last change might have broken this...

Screen Shot 2020-10-09 at 2 13 38 PM

**Comment by kierancott** [comment]
## Updated

I've changed all components to use `state.user_id` rather than `state.user.user.id`, because the `user: { ... }` object changes structure whereas `user_id` will remain constant.

Since I've changed all the instances of `state.user.user.id` to `state.user_id`, not just the `StageTracker.js`, this _should_ stop this type of error across the whole app.

Thanks for your thorough testing, let me know if you find any more pesky bugs.

**Review by nosvalds — CHANGES_REQUESTED** [review]
# One more issue (I hope)
- When adding a new job and not changing the interview format drop down, I'm getting a failed POST request for creating the Interview. Looks like the format is being sent as "select"
image

image

**Comment by nosvalds** [comment]
## New issues 
From our Slack discussion
- Adding a new Job - if you leave the first form blank it fails to create a job because we have (title, company, active, stage) required on the backend. I would make "Title" and "Company" required in that form's HTML. I think that would be simplest and is reasonable to expect they filled out that much at least.
- Adding new Job - When you leave Application Notes or Interviews blank the front end should not make a POST request

**Comment by kierancott** [comment]
## Updated:

- Added form validation for title and company field on job form. User cannot proceed to next step without filling in these fields.

Screenshot 2020-10-09 at 15 37 41

- Added conditions to the three requests that are sent upon submission of the add job form.
1. Application Notes: will not POST to `api/user/id/jobs/id/app-notes` if the `data` property is blank.
2. Interviews: will note POST to `api/user/id/jobs/id/interviews` if the `date` property is blank
3. CV/Cover Letter: will not PATCH to `api/user/id/jobs/id/interviews` if both the `cv` and `cover_letter` are blank (but it will if one of them is left blank).

**Review by nosvalds — APPROVED** [review]

**Comment by kierancott** [comment]
## Post-Approval Update:

Thanks, Nik. Just a quick fix to a small issue that fell through the cracks:

**Issue:** Sending both CV and cover letter, or neither, works - but if you send only one, the API returns `Error 422` because the API does not accept an empty string for either value.

**Action:** Added conditions to the form submission function, that will exclude the CV or Cover letter from the PATCH request if it is left blank

**Review by nosvalds — APPROVED** [review]
# Looks good!

**Pull request merged**
