### PR TITLE
User account page and auth functionality

### PR DESCRIPTION
**Pull request by aejgardner**
- 3 user account components created and functionality added to update and delete user account.
- custom hook and helper function made for front end login / register / forgot password request validation.
- private route component created for protected components.
- combineReducers() no longer used.
- forgot password and password reset components created, functionality added.
- fourohfour component created.
- header component created.
- axios routes corrected.

### CODE REVIEW

**Review by nosvalds — CHANGES_REQUESTED** [review]
I've installed locally to test with the development branch of the backend. Here are the issues I encountered trying out some of the workflows

## Issues
- When registering or logging in a user I'm redirected to `/dashboard` and get a 404 that no page exists for that route
  - line 32 and 71 in actions.js should be updated to `/mainpage`

- Logging in is using the route `/user/login` currently backend is just using `/login`
  - update auth.js line 14 to be `/login`

- Login API returns data.user.id, not data.id which I "think" the front end is assuming and storing into state with the data: part
image

- Getting failed API requests going to the main page, Header does not seem to include the Bearer Token. Can't see where that gets stored on the response from Login.

- Login.js - line 73 - redirects to /home/forgot-password, should be /forgot-password

- Reset Password without token form is not sending the email in the body of the request
  - auth.js - don't seem to be sending a body with this request should be { email: <email> }
image

**Review by kierancott — COMMENTED** [review]
Lots of good stuff here.

Since I don't have a machine to test this on at the moment, I'll leave it to @nosvalds to ensure this is what he was expecting and approve.

**Review by nosvalds — CHANGES_REQUESTED** [review]
Good progress! Here are my issues encountered from testing again against the up to date backend. The login/authentication issue is the highest priority to allow for additional testing.

## Issues
### Account Registration - error handling
- I tried to register an account with an email that was already in the database, should fail more gracefully and tell the user this... getting a bad error.
image

### Login
- As discussed, Front end needs to store the access_token (bearer) and include it on requests to the back end. The login request is good and returns the right info from the backend.
image

### Reset Password
- Email works! Did have to submit 2x ( think that is a backend problem though)
- No visual indication on front end that email has been sent successfully for the password reset. Response is sent from the backend that you could use:
image

### Password reset (with token)
- The URL supplied in the email is not hitting a route. 
  - E.g.: http://localhost:3000/password-reset/?email=nik%40nikolaso.com&token=fR7oRdqYuCgPms2N2QzSxMMCZsGX9aO8hke9l4bFGbqpbn1YIYnwn0jE5lUc
- after the "?" are query parameters, the route right now is configured to take /password-reset/:token, I think this needs to be updated to take the 2 query parameters somehow
 - In App.js

**Comment by kierancott** [comment]
# Issues Resolved

### Account registration - error handling, Issue https://github.com/develop-me/bagajob/issues/43

**Action:**

- extract error message from state and render below form
- create function that clears errors on form load

**Result:**

Instead of the app crashing due to unprocessable entity, the below error is shown:

Screenshot 2020-09-19 at 15 28 08

### Login, Issue https://github.com/develop-me/bagajob/issues/44

**Action:**

Bearer token has been added to the header of the request.

**Result:**

200 - OK: API now approves access and loads main page with code 200.

Screenshot 2020-09-18 at 17 57 40

### Reset Password, Issue https://github.com/develop-me/bagajob/issues/45

Commit: https://github.com/develop-me/bagajob/commit/201f10d8c076628ff3c3c7c042550c7c56917daf

**Action:**

- Added `useEffect` function that clears `authResponse` on component load
- Rendered `authResponse` as `<p>` element below form

**Result:**

Feedback is given to user while loading, and when email is sent - instructing them to check their inbox.

Screenshot 2020-09-20 at 17 58 56

### Reset password (with token), Issue https://github.com/develop-me/bagajob/issues/46

**Action:**

- Installed `use-query-params` and `query-string` npm packages
- Wrapped all React Routes with `<QueryParamProvider ReactRouterRoute={Route}>`
- Created hooks to extract email and token from URL and dispatch with password

**Result:**

- Email and token are correctly extracted from the URL and posted to the API in format:
`{email: "email@email.com", password: "newpassword", token: "tokenstring47HFD98SJNFUIhki93"}`

Screenshot 2020-09-21 at 15 33 19

# Other issues resolved by this Pull Request:

### Logout functionality, Issue https://github.com/develop-me/bagajob/issues/49

Commits
https://github.com/develop-me/bagajob/pull/42/commits/3a0938cecb37a54388c621b722b3193f2eb3ef7d
https://github.com/develop-me/bagajob/pull/42/commits/fe2857b9a0d84667a245b30efaa334e02709c9cb

**Action:**

- Created route at `api/home/logout`
- Created logout reducer to clear user (and thus bearer token) from state
- Redirect user to login page

**Result:**

Visiting `api/home/logout` and clicking "Log Out" now clears state and prompts user to return to login

Screenshot 2020-09-19 at 17 30 20

Screenshot 2020-09-19 at 17 42 07

More styling still required.

### Single job - user ID undefined, Issue https://github.com/develop-me/bagajob/issues/50

Commit https://github.com/develop-me/bagajob/pull/42/commits/ee491d805cecd146b292fd2ccf8327c06a1dfc17, https://github.com/develop-me/bagajob/pull/42/commits/e09682b977347eefbc961bd925a35025ee07e000

**Action:**

- `user_id` is now used correctly in the URL
- Bearer token has been added to the header of the request.

Screenshot 2020-09-19 at 00 28 33

**Review by nosvalds — CHANGES_REQUESTED** [review]
## Working
- Login issue #44 - Fixed
- issue #45 
- Forgot password (without token) route works and sends an email appropriately!
- Can login with an existing user (e.g. bagajob.mail@gmail.com)

## Issues encountered
- General feedback - the errors displayed to the User in the front end should be non-programmery, so no mention of status codes, etc. - could be a good one to give to a new person and probably not necessary to fix for MVP since we're short on time.

- Issue #43 - see issue

- When I register a new user, the POST route for registration works fine, however the Client then makes a GET request for UserID 5's jobs and bombs out... my guess is that state is not getting updated with the User sent back from the backend on successful registration. You might not be seeing it if you're staying in the same browser session and not fully clearing state before trying registration again.
image

- When I get through adding a new job, the post request is bombing out because `active` and `stage` are not being sent in the POST request
image

- #46 When resetting password Client doesn't seem to send token, email, password to server. Getting this failure:
image
image

- When I enter an incorrect password on logging in, I see the error on the screen for a short period then it bombs out:
image
image

**Comment by kierancott** [comment]
## Working
- Login issue #44 - Fixed
- issue #45 
- Forgot password (without token) route works and sends an email appropriately!
- Can login with an existing user (e.g. bagajob.mail@gmail.com)

## Issues encountered
- General feedback - the errors displayed to the User in the front end should be non-programmery, so no mention of status codes, etc. - could be a good one to give to a new person and probably not necessary to fix for MVP since we're short on time.

- Issue #43 - see issue

- When I register a new user, the POST route for registration works fine, however the Client then makes a GET request for UserID 5's jobs and bombs out... my guess is that state is not getting updated with the User sent back from the backend on successful registration. You might not be seeing it if you're staying in the same browser session and not fully clearing state before trying registration again.
image

- When I get through adding a new job, the post request is bombing out because `active` and `stage` are not being sent in the POST request
image

- #46 When resetting password Client doesn't seem to send token, email, password to server. Getting this failure:
image
image

- When I enter an incorrect password on logging in, I see the error on the screen for a short period then it bombs out:
image
image

**Comment by kierancott** [comment]
Closed in error.

**Comment by kierancott** [comment]
## Updated Issues

### _- ~~General feedback - the errors displayed to the User in the front end should be non-programmery, so no mention of status codes, etc. - could be a good one to give to a new person and probably not necessary to fix for MVP since we're short on time.~~_ 

Moved to separate issue for a later date post-MVP (Issue https://github.com/develop-me/bagajob/issues/55)

### _- ~~Issue #43 - see issue~~_

Now resolved
Commit https://github.com/develop-me/bagajob/pull/42/commits/b68f7d7c0eec210c3aa2d5f9e91c14a6db8006e8

### _- ~~When I get through adding a new job, the post request is bombing out because `active` and `stage` are not being sent in the POST request~~_

Now resolved, active and stage are included in the POST request.
Commit https://github.com/develop-me/bagajob/pull/42/commits/bc52e8dc009e03c547dc4596b15eba7a53c89212

### _- ~~#46 When resetting password Client doesn't seem to send token, email, password to server.~~_

(Issue https://github.com/develop-me/bagajob/issues/46) Email, token and password now being correctly sent and backend returns 200 OK.
Commit https://github.com/develop-me/bagajob/pull/42/commits/b68f7d7c0eec210c3aa2d5f9e91c14a6db8006e8

### _- ~~When I enter an incorrect password on logging in, I see the error on the screen for a short period then it bombs out:~~_

Now resolved
Commit https://github.com/develop-me/bagajob/pull/42/commits/b68f7d7c0eec210c3aa2d5f9e91c14a6db8006e8

## Unresolved issues

_When I register a new user, the POST route for registration works fine, however the Client then makes a GET request for UserID 5's jobs and bombs out... my guess is that state is not getting updated with the User sent back from the backend on successful registration. You might not be seeing it if you're staying in the same browser session and not fully clearing state before trying registration again._

image

I'm having trouble reproducing this behaviour. 

- I registered a new user, User 17 (`{ name: "Jimmy", email: "jimmy@
jimmy.com", password: "jimmy1" }`) with status code 200 OK. Then I've made sure to clear state using the logout route:

State cleared:
Screenshot 2020-09-22 at 13 06 23
Screenshot 2020-09-22 at 13 06 36

- Logging in with the new user login is successful with status code 200 OK.

Screenshot 2020-09-22 at 13 07 08

Here's what was sent:

Screenshot 2020-09-22 at 13 07 11 (2)

Here's what was returned:

Screenshot 2020-09-22 at 13 07 31

- The client side then routes to GET `api/user/17/jobs`, which is successful with status code 200.

Screenshot 2020-09-22 at 13 07 41

The bearer token is correctly included in the authorisation header:

Screenshot 2020-09-22 at 13 17 10

_In this case, no data is returned since no jobs are associated with this new user_

**Comment by kierancott** [comment]
## Updated Issues

~~_When I register a new user, the POST route for registration works fine, however the Client then makes a GET request for UserID 5's jobs and bombs out... my guess is that state is not getting updated with the User sent back from the backend on successful registration. You might not be seeing it if you're staying in the same browser session and not fully clearing state before trying registration again._~~

image

Now resolved
Commit https://github.com/develop-me/bagajob/pull/42/commits/9cfcb733717c7c4645573477277570941f1d09b9

When a POST request is made to `/register`, the bearer token is included in the header, resulted in status 200 OK when redirected to `/user/:id/jobs`

**Review by nosvalds — COMMENTED** [review]
## Fixed
- ***FIXED*** - #43
- ***FIXED*** - When I register a new user, the POST route for registration works fine, however the Client then makes a GET request for UserID 5's jobs and bombs out... my guess is that state is not getting updated with the User sent back from the backend on successful registration. You might not be seeing it if you're staying in the same browser session and not fully clearing state before trying registration again.
- ***FIXED*** - When I get through adding a new job, the post request is bombing out because active and stage are not being sent in the POST request
- ***FIXED*** - #46 
- ***FIXED*** - When I enter an incorrect password on logging in, I see the error on the screen for a short period then it bombs out.

**Comment by nosvalds** [comment]
## To Do
- User account page doesn't display the logged in user or query the backend appropriately
image

**Comment by kierancott** [comment]
### Update:

- User's name and initials lifted from state and rendered on account page
- Navbar component completed and user initials rendered in top right corner

Screenshot 2020-09-23 at 15 31 52

**Review by nosvalds — CHANGES_REQUESTED** [review]
## Updates
- User Account Page -  I can now login with a user and go to my account page!
- Logout - This worked as well!

## To do
- PATCH/DELETE requests to update Account Name/Email or Delete the account are failing due to being "Unauthorized" (guessing it's not sending the bearer token)

**Comment by kierancott** [comment]
### Update:

- Bearer token now included in PATCH & DELETE requests to `api/user/:id`
- Error message is displayed `Request failed with status code 422` if a bad name or email is sent
- Name and initials dynamically update on successful PATCH request

- PATCH `api/user/:id` - Returns 200 OK
- DELETE `api/user/:id` - Returns 204 No Content

**Review by nosvalds — APPROVED** [review]
## Review
- Name Change PATCH working
- Email change PATCH working
- DELETE account working

# APPROVED

**Pull request merged**
